version: "3.2"

services:

#### Ubuntu ##################################
    ubuntu-docker-offline:
      build:
        context: ./Ubuntu
      environment:
        RELEASE: ${RELEASE}
        ARCH: ${ARCH}
      volumes:
      - ./Ubuntu:/home/docker

#### Ubuntu test ##################################
    ubuntu-test:
      image: amd64/ubuntu:14.04
      command: tail -f /dev/null
      working_dir: /home/docker
      volumes:
      - ./Ubuntu:/home/docker

#### Debian ##################################
    debian-docker-offline:
      build:
        context: ./Debian
      environment:
        RELEASE: ${RELEASE}
        ARCH: ${ARCH}
      volumes:
        - ./Debian:/home/docker

#### Debian test ##################################
    debian-test:
      build:
        context: ./Debian
        dockerfile: ./test.Dockerfile
      volumes:
        - ./Debian:/home/docker

#### Centos ##################################
    centos-docker-offline:
      build:
        context: ./Centos
        args:
          RELEASE: ${RELEASE}
      environment:
        RELEASE: ${RELEASE}
        ARCH: ${ARCH}
      volumes:
        - ./Centos:/home/docker

#### Centos test ##################################
    centos-test:
      image: amd64/centos:7
      command: tail -f /dev/null
      working_dir: /home/docker
      environment:
        RELEASE: 7.8.2003
      volumes:
        - ./Centos:/home/docker